services:
  thepantry:
    image: thepantry:latest
    build:
      context: ./ThePantry
      dockerfile: src/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ./data:/db
      - ./data/uploads:/uploads
    restart: unless-stopped