// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThePantry.Data;

#nullable disable

namespace ThePantry.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225182054_AddImagePathToScanQueueItem")]
    partial class AddImagePathToScanQueueItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ThePantry.Domain.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pantry");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OnHandCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("ThePantry.Domain.ProductSku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("ProductSkus");
                });

            modelBuilder.Entity("ThePantry.Domain.ScanQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LinkedInventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Upc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedInventoryItemId");

                    b.HasIndex("Status");

                    b.HasIndex("Upc");

                    b.ToTable("ScanQueueItems");
                });

            modelBuilder.Entity("ThePantry.Domain.UsageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("Timestamp");

                    b.ToTable("UsageHistories");
                });

            modelBuilder.Entity("ThePantry.Domain.ProductSku", b =>
                {
                    b.HasOne("ThePantry.Domain.InventoryItem", "InventoryItem")
                        .WithMany("Skus")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("ThePantry.Domain.ScanQueueItem", b =>
                {
                    b.HasOne("ThePantry.Domain.InventoryItem", "LinkedInventoryItem")
                        .WithMany()
                        .HasForeignKey("LinkedInventoryItemId");

                    b.Navigation("LinkedInventoryItem");
                });

            modelBuilder.Entity("ThePantry.Domain.UsageHistory", b =>
                {
                    b.HasOne("ThePantry.Domain.InventoryItem", "InventoryItem")
                        .WithMany("UsageHistories")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("ThePantry.Domain.InventoryItem", b =>
                {
                    b.Navigation("Skus");

                    b.Navigation("UsageHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
